# -*- coding: utf-8 -*-
"""py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I1Plef33kR-c3cXevYbPFk96EPjM2Zce
"""

from pickleshare import print_function
n=float(input("Enter Input Number 1: "))
m=float(input("Enter Input Number 2: "))
print("The Addition is: ",n+m)

a=float(input("Enter The Fast Number: "))
b=float(input("Enter The Secend Number: "))
c=float(input("Enter The Third Number: "))
d=float(input("Enter The Fourth Number: "))
e=float(input("Enter The Fifth Number: "))
if (a>b) and (a>c) and (a>d) and (a>e):
  print("This Nummber Larger Than Other Number", a)
elif (b>a) and (b>c) and (b>d) and (b>e):
  print("This Nummber Larger Than Other Number",b)
elif (c>a) and (c>b) and (c>d) and (c>e):
  print("This Nummber Larger Than Other Number",c)
elif (d>a) and (d>b) and (d>c) and (d>e):
  print("This Nummber Larger Than Other Number",d)
elif (e>a) and (e>b) and (e>c) and (e>d):
  print("This Nummber Larger Than Other Number",c)
else:
  Print("Invalod")

print("Please Write: Brilliant, or Better, or Good, or Nothing")
a =(str (input("Enter Your Valu: ")))
if a == "Brilliant":
  print("The Student is more active and sincere")
elif a == "Better":
  print("The Student is trying join extra curriculam Activities")
elif a == "Good":
  print("The Student is larn about extra curriculam activities")
elif a == "Nothing":
  print("The student is not join any Extra curriculam")
else:
  Print("Invalod")

fst = float(input("Enter the 1st Valu : "))
sec = str(input("Enter The Operator: "))
thd = float(input("Enter the 2nd Valu :  "))

if sec == "+":
  print(fst+thd)
elif sec == "-":
  print(fst-thd)
elif sec == "*":
  print(fst*thd)
elif sec == "/":
  print(fst/thd)
else:
  print("Invalid Function")

#Initialize array     
arr = [5, 2, 8, 7, 1, 6, 10, 14, 17, 3];     
temp = 0;    
     
#Displaying elements of original array    
print("Elements of original array: ");    
for i in range(0, len(arr)):     
    print(arr[i]),    
     
#Sort the array in descending order    
for i in range(0, len(arr)):    
    for j in range(i+1, len(arr)):    
        if(arr[i] < arr[j]):    
            temp = arr[i];    
            arr[i] = arr[j];    
            arr[j] = temp;    
     
print();    
     
#Displaying elements of array after sorting    
print("Elements of array sorted in descending order: ");    
for i in range(0, len(arr)):     
    print(arr[i]),

print("Enter Marks Obtained in 5 Subjects: ")
markOne = int(input())
markTwo = int(input())
markThree = int(input())
markFour = int(input())
markFive = int(input())

tot = markOne+markTwo+markThree+markFour+markFive
avg = tot/5

if avg>=91 and avg<=100:
    print("Your Grade is A1")
elif avg>=81 and avg<91:
    print("Your Grade is A2")
elif avg>=71 and avg<81:
    print("Your Grade is B1")
elif avg>=61 and avg<71:
    print("Your Grade is B2")
elif avg>=51 and avg<61:
    print("Your Grade is C1")
elif avg>=41 and avg<51:
    print("Your Grade is C2")
elif avg>=33 and avg<41:
    print("Your Grade is D")
elif avg>=21 and avg<33:
    print("Your Grade is E1")
elif avg>=0 and avg<21:
    print("Your Grade is E2")
else:
    print("Invalid Input!")

print("Enter Marks Obtained in 1 Subjects: ")
markOne = int(input())

if markOne>=80 and markOne<=100:
    print("Your Grade is A+")
elif markOne>=75 and markOne<79:
    print("Your Grade is A")
elif markOne>=70 and markOne<74:
    print("Your Grade is A-")
elif markOne>=65 and markOne<69:
    print("Your Grade is B+")
elif markOne>=60 and markOne<64:
    print("Your Grade is B-")
elif markOne>=55 and markOne<59:
    print("Your Grade is D")
elif markOne>=50 and markOne<54:
    print("Your Grade is C+")
elif markOne>=41 and markOne<49:
    print("Your Grade is C-")
elif markOne>=0 and markOne<40:
    print("Your Grade is F")
else:
    print("Invalid Input!")

i = int(input())

while i >= 0:
  print(i)
  i -= 1